name: Deploy to Github Pages
run-name: ${{ github.actor }} is deploying to github pages
on:
  push:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Install ruby
        run: |
          sudo apt-get remove ruby
          sudo apt-get install ruby
      - name: Install jekyll
        run: sudo gem install bundler jekyll
      - name: Check out repository code in the master branch
        uses: actions/checkout@v3
        with:
          ref: 'master'
      - name: debug -> check branch
        run: git rev-parse --abbrev-ref HEAD
      - run: pwd
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: ls ~
      - name: Build site
        run: bundle exec jekyll build
      - name: copy around output
        run: |
          mkdir ../output
          cp -r _site/* ../output/
          git checkout gh-pages
          git clean -fd
      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@jaffboys.com"
          git config --local user.name "github-actions[bot]"
      - name: Git pull 
        run: git pull
      - name: Checkout to gh-pages
        run: git checkout gh-pages
      - name: copy docs folder into gh-pages branch (agh this is hacky but whatever)
        run: cp -r ../output/* ./docs/
      - name: Add files
        run: git add .
      - name: commit and push files
        run: |
          git commit -a -m "Publish Blog"
          git push
      - run: echo "🍏 This job's status is ${{ job.status }}."
